exchange_allowlist:
  - NYSE
  - NASDAQ
  - AMEX
min_price: 3.0
min_dollar_volume: 2000000.0
min_avg_volume_20d: 1000000.0
min_market_cap: 1000000000.0
asset_type_allowlist:
  - EQUITY
exclude_fund_like_names: true
min_fundamental_quarters: 6
